#### GHStudios
#### https://gamehoundsinteractive.com
#### Version 2.0

sql:
  host: 'localhost'  
  database: db
  username: name
  password: pass
  port: 3306
  
settings:
  checktime: 60 ## Coming Soon! Time it auto checks to see if new purchases
  autocheck: false ## Coming Soon! Turns on auto checking
  Permission: licenseredeem.redeem ## Currently Added
  APIKey: "" ## Coming Soon! Create a IPS API key and paste it here  https://invisioncommunity.com/developers/rest-api/index/
  config-version: 2.0 ## Do Not Touch!